# Generated by Django 5.1.7 on 2025-06-25 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('priority', models.SmallIntegerField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
                ('slot_choices', models.ManyToManyField(to='scheduler.datetimeslot')),
            ],
            options={
                'unique_together': {('organization', 'faculty_id')},
            },
        ),
    ]
