# Generated by Django 5.1.7 on 2025-06-25 11:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('faculty', '0001_initial'),
        ('group', '0001_initial'),
        ('organization', '0001_initial'),
        ('room', '0001_initial'),
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveSmallIntegerField(blank=True, default=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='faculty.faculty')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.group')),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_slot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.datetimeslot')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='room.room')),
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='timetable.section')),
            ],
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timetable_id', models.CharField(max_length=50)),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1900, message='Year cannot be less than 1900'), django.core.validators.MaxValueValidator(limit_value=2100, message='Year cannot be more than 2100')])),
                ('semester', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
            options={
                'unique_together': {('organization', 'timetable_id')},
            },
        ),
        migrations.AddField(
            model_name='section',
            name='timetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.timetable'),
        ),
        migrations.CreateModel(
            name='ScheduleStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure')], default='PENDING', max_length=10)),
                ('task_id', models.CharField(blank=True, max_length=100, null=True)),
                ('last_run_at', models.DateTimeField(auto_now=True)),
                ('timetable', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='timetable.timetable')),
            ],
        ),
    ]
