# Generated by Django 5.1.7 on 2025-04-03 19:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='year',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1900, message='Year cannot be less than 1900'), django.core.validators.MaxValueValidator(limit_value=2100, message='Year cannot be more than 2100')]),
        ),
    ]
