# Generated by Django 5.1.7 on 2025-04-05 16:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0001_initial"),
        ("timetable", "0002_alter_timetable_created_at_alter_timetable_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="timetable",
            name="timetable_id",
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="timetable",
            unique_together={("organization", "timetable_id")},
        ),
    ]
