# Generated by Django 5.1.7 on 2025-03-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('days_per_week', models.PositiveSmallIntegerField()),
                ('slots_per_day', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
