# Generated by Django 5.1.7 on 2025-03-22 07:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField()),
                ('time', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('priority', models.SmallIntegerField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.organization')),
                ('slot_choices', models.ManyToManyField(to='scheduler.datetimeslot')),
            ],
            options={
                'unique_together': {('organization', 'faculty_id')},
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=50)),
                ('size', models.PositiveSmallIntegerField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.organization')),
            ],
            options={
                'unique_together': {('organization', 'group_id')},
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('is_lab', models.BooleanField(blank=True, default=False)),
                ('capacity', models.PositiveSmallIntegerField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.organization')),
            ],
            options={
                'unique_together': {('organization', 'room_id')},
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.organization')),
                ('rooms', models.ManyToManyField(blank=True, to='scheduler.room')),
            ],
            options={
                'unique_together': {('organization', 'course_id')},
            },
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1900, message='Year cannot be less than 1900'), django.core.validators.MinValueValidator(limit_value=2100, message='Year cannot be more than 2100')])),
                ('semester', models.CharField(max_length=20)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveSmallIntegerField(blank=True, default=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.course')),
                ('date_time_slot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.datetimeslot')),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.faculty')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.group')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.room')),
                ('time_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.timetable')),
            ],
        ),
    ]
